name: Alerta Diário - Sites com Baixa Receita

on:
  schedule:
    # Executa todos os dias às 9:00 AM (horário de Brasília = UTC-3, então 12:00 UTC)
    - cron: '0 12 * * *'
  workflow_dispatch:  # Permite execução manual

jobs:
  run-alerta:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache dependências
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Criar arquivo .env
      run: |
        echo "CLICKHOUSE_URL=${{ secrets.CLICKHOUSE_URL }}" >> .env
        echo "CLICKHOUSE_DATABASE=${{ secrets.CLICKHOUSE_DATABASE }}" >> .env
        echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> .env
        echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> .env
        echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> .env
        echo "MENTION_IDS=${{ secrets.MENTION_IDS }}" >> .env
        
    - name: Executar script de alerta
      run: python alerta_oficial.py
      
    - name: Upload do arquivo CSV (se gerado)
      uses: actions/upload-artifact@v4
      if: always()  # Executa mesmo se o script falhar
      with:
        name: relatorio-sites-${{ github.run_number }}
        path: sites_cost_pos_lowrev_yday_with_domain.csv
        retention-days: 30
        
    - name: Notificar falha (opcional)
      if: failure()
      run: |
        echo "❌ Script falhou! Verifique os logs do workflow."
        # Aqui você poderia adicionar uma notificação adicional se desejar
